# Generated by Django 3.1.2 on 2021-04-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Semesters',
            new_name='Semester',
        ),
    ]
