# Generated by Django 3.1.7 on 2021-04-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20210401_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.course')),
            ],
        ),
    ]
