# Generated by Django 3.1.7 on 2021-04-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='prereq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.course'),
        ),
    ]
